substitutions:
  device_name: 'esp-stand-up-desk'
  friendly_name: 'Stand Up Desk'
  ap_pw: 'L2i5rbTy5Fa7'
  ssid: !secret wifi_ssid
  ssid_pw: !secret wifi_password

esphome:
  name: '${device_name}'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  logs:
    ble_sensor: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret display_key

ota:
  - platform: esphome
    password: !secret display_ota

wifi:
  ssid: $ssid
  password: $ssid_pw
  manual_ip:
    static_ip: 10.2.10.19
    gateway: 10.2.10.254
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: AP_${device_name}
    password: $ap_pw
# Only for arduino framework
captive_portal: 

# BEGIN TIMOTION INTEGRATION
external_components:
  # - source:
  #     type: local
  #     path: components
  - source: github://Klumpke/esphome-timotion-desk-controller@main
    components: [ timotion_desk_controller ]
    refresh: 0s

globals:
  # To store the Desk Connection Status
  - id: desk_client_connected
    type: bool
    initial_value: 'false'

esp32_ble_tracker:

ble_client:
  - mac_address: 'DD:B5:D0:6B:D9:BC'
    id: timotion_desk
    on_connect:
      then:
        # Update the Desk Connection Status
        - lambda: |-
            id(desk_client_connected) = true;
        - delay: 5s
        # Update desk height and speed sensors after bluetooth is connected
        - lambda: |-
            id(desk_state).update();
            id(desk_height).update();
    on_disconnect:
      then:
        # Update the Desk Connection Status
        - lambda: |-
            id(desk_client_connected) = false;

timotion_desk_controller:
  ble_client_id: timotion_desk
  # Optional -- todo remove
  only_up_down_command: true

number:
  - platform: timotion_desk_controller
    id: desk_target_height
    name: '${friendly_name} Height'
    mode: slider
    icon: mdi:desk

button:
  - platform: template
    name: '${friendly_name} Up'
    icon: 'mdi:arrow-up-bold'
    on_press:
      then:
        - number.set:
            id: desk_target_height
            value: !lambda 'return id(desk_height).state + 1.0f;'

  - platform: template
    name: '${friendly_name} Down'
    icon: 'mdi:arrow-down-bold'
    on_press:
      then:
        - number.set:
            id: desk_target_height
            value: !lambda 'return id(desk_height).state - 1.0f;'

sensor:
  # Desk Height Sensor
  - platform: ble_client
    type: characteristic
    ble_client_id: timotion_desk
    id: desk_height
    name: '${friendly_name} Height'
    service_uuid: '6e400001-b5a3-f393-e0a9-e50e24dcca9e'
    characteristic_uuid: '6e400003-b5a3-f393-e0a9-e50e24dcca9e'
    icon: 'mdi:arrow-up-down'
    unit_of_measurement: 'cm'
    accuracy_decimals: 1
    update_interval: never
    notify: true
    # filters:
    #   - lambda: |-
    #       static float last_value = NAN;
    #       if (x != last_value) {
    #         last_value = x;
    #         return x;
    #       }
    #       return {};
    # or just delta filter :D
    filters:
      - delta: 0.1
    lambda: |-
      uint16_t raw_height = x[3];
      unsigned short height_mm = raw_height;
      return (float) height_mm;

  # Desk Speed Sensor
  - platform: ble_client
    type: characteristic
    ble_client_id: timotion_desk
    id: desk_state
    name: '${friendly_name} State'
    service_uuid: '6e400001-b5a3-f393-e0a9-e50e24dcca9e'
    characteristic_uuid: '6e400003-b5a3-f393-e0a9-e50e24dcca9e'
    icon: 'mdi:arrow-split-horizontal'
    accuracy_decimals: 0
    update_interval: never
    notify: true
    filters:
      - delta: 0.1
    lambda: |-
      uint16_t raw_speed = x[1];
      if (raw_speed == 65) return -1;
      if (raw_speed == 66) return 1;
      return 0;

binary_sensor:
  # Desk Bluetooth Connection Status
  - platform: template
    name: '${friendly_name} Connection'
    icon: 'mdi:bluetooth'
    id: desk_connection
    lambda: 'return id(desk_client_connected);'

  # Desk Moving Status
  - platform: template
    name: '${friendly_name} Moving'
    id: desk_moving
    icon: 'mdi:engine'
    lambda: 'return abs(id(desk_state).state) == 1;'
    # lambda: |-
    #   if (id(desk_state).state >= -1 && id(desk_state).state <= 1) return abs(id(desk_state).state) == 1;
    #   return invalid;
